name: Build Electron App
on:
  push:
    tags:
      - 'v*' # ඔබ GitHub එකේ v1.0 වැනි tag එකක් දැමූ විට මෙය ක්රියාත්මක වේ

jobs:
  release:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        shell: pwsh
        run: |
          $env:ELECTRON = 'true'
          npm run build

      - name: Build and Publish EXE
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
