name: Build Electron App
on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  release:
    types: [created]

jobs:
  release:
    permissions:
      contents: write
    runs-on: windows-latest
    env:
      ELECTRON: true
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build and Publish EXE
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build:win
          release: true
